### ISSUE TITLE
Fails to verify once the size is big

### ISSUE THREAD

**Issue by fabiodl** [MarsTechHAN/ch552tool#17]
In several projects, the tool works flawlessly for small files. Once I reach a certain size, it stars giving this kind of error

`python3 -m ch55xtool  -f build/fat32.bin -r

Found CH559.

BTVER: V2.40.

Failed to verify firmware of CH55x.`

I attach a CH559 binary file that fails. In all the cases, the official programmer works.

[fat32.zip](https://github.com/MarsTechHAN/ch552tool/files/6324179/fat32.zip)

**Comment by MarsTechHAN** [comment]
Sorry I got so busy recently. I will take a look.

**Comment by fabiodl** [comment]
Thank you! let me know if you need other binaries that fail.

**Comment by frank-zago** [comment]
The problem is likely with the erase command. It only erases 8 KB. The length needs to be adjusted to the size of the firmware being flashed.

The 0x08 is the size. Change it to 0x10, and it should work.
ERASE_CHIP_CMD_V2 = [0xa4, 0x01, 0x00, 0x08]

**Comment by fabiodl** [comment]
Thanks, that seems to fix the issue!

**Comment by Pe3ucTop** [comment]
Latest original software pass sizes in 32 bits also. 
For my 192kb chip erase original soft send : 
 [0xA4, 0x04, 0x00, 0xC0, 0x00, 0x00, 0x00] 
0xA4  - erase 
0x0004  - command payload size = 4 byte = 32 bit 
0x000000c0 = 192  = so 192   1k pages to erase

**Comment by frank-zago** [comment]
Indeed. I've also used 4 bytes for that command, even on a CH551 with a 2.3.1 bootloader. I think the bootloader is too small to have extra checks.

**Comment by MarsTechHAN** [comment]
> The problem is likely with the erase command. It only erases 8 KB. The length needs to be adjusted to the size of the firmware being flashed.
> 
> The 0x08 is the size. Change it to 0x10, and it should work. ERASE_CHIP_CMD_V2 = [0xa4, 0x01, 0x00, 0x08]

See that... I should really fix it. Welcome PR for that :p

**Comment by Maksons** [comment]
Sorry, your latest commit has wrong divisor for erase size calculation !
>+    erase_size = math.ceil(binary_size/0x1000) & 0xff
but should be :
/ 1024  or / 0x400

**Comment by Pe3ucTop** [comment]
Sorry, your latest commit has wrong divisor for erase size calculation !

erase_size = math.ceil(binary_size/0x1000) & 0xff
but should be :
/ 1024 or / 0x400
because it is in 1k pages
