### ISSUE TITLE
Cannot use Zadig with Maix Bit due to "[Port2] FailedEnumeration: Unknown USB Device (Device Descriptor Request Failed)"

### ISSUE THREAD

**Issue by etheory** [MarsTechHAN/ch552tool#19]
Hi there.

I have tried to follow your instructions to fix an issue someone suggested here: https://en.bbs.sipeed.com/t/topic/2484 could be fixed using Zadig. Unfortunately, I cannot flash a device that I cannot even get to enumerate properly.

Also, when I attempt to update the driver to the Maix Bit Zadig says: "Driver Installation: FAILED (Resource already exists)".

I found another thread that suggested turning off the USB device then turning it back on and trying again would allow Zadig to install the driver on the second attempt. That does not work with the Maix Bit.

Any advice would be appreciated.

**Comment by MarsTechHAN** [comment]
I have never met this before, maybe you should ask in StackOverflow? My suspect is that some system takes the control of the device. Can you try to uninstall (and remove the driver) in the device manager, and then use zadig to install the driver?

**Comment by MarsTechHAN** [comment]
oh... if it even cannot enumerate, that means there should be something wrong with the hardware...

**Comment by etheory** [comment]
Yeah it looks like there are issues with the drivers themselves, since through a USB Hub, I'm able to enumeratet the MAIX Bit properly. So the sipeed drivers for Windows appear to be broken on Windows 10 unless you have a Hub. So yeah, this isn't your fault ;-).
