### ISSUE TITLE
README does not mention CH56x also work now

### ISSUE THREAD

**Issue by hansfbaier** [MarsTechHAN/ch552tool#24]
The README and project description need to mention CH56x and Version 2.70
I have tested the tool successfully with CH569.

**Comment by hansfbaier** [comment]
@vowstar The README still doesnt show that information and that change, does not seem to address it.

**Comment by vowstar** [comment]
Thank you very much for the reminder, this was caused by a rebase error and has been re-corrected

**Comment by hansfbaier** [comment]
You're welcome. Also updating the project description would be nice!
