### ISSUE TITLE
Support Mac OS

### ISSUE THREAD

**Issue by sabas1080** [MarsTechHAN/ch552tool#6]
Hi @MarsTechHAN 

I am testing this script and not work in Mac OS, python3 with CH559

Chip is always in mode boot

Thanks

**Comment by MarsTechHAN** [comment]
Hi,
The script was tested on various macOS version，so it should work in macOS, but I actually didn't test on CH559 yet.
Can you upload the log here, you said the chip is always in boot mode, which means that you did finish the whole process of the script? And also, did you make sure your program file is working and not corrupted.

**Comment by sabas1080** [comment]
The script support file .hex or only .bin?

**Comment by MarsTechHAN** [comment]
Oh, it's now only support bin... I might add it when I got time. You can use convert hex to bin by objdump
```bash
objcopy --input-target=ihex --output-target=binary code00.hex code00.bin
```
